name: Renso
options:
  bundleIdPrefix: com.denysrumiantsev
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_PREVIEWS: "YES"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: "YES"
    INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    SWIFT_STRICT_CONCURRENCY: complete
    SWIFT_UPCOMING_FEATURE_EXISTENTIAL_ANY: "YES"

packages:
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    from: "3.0.0"

targets:
  Renso:
    type: application
    platform: iOS
    sources:
      - path: Renso
        excludes:
          - "**/*.md"
    resources:
      - path: Renso/Resources/Assets.xcassets
      - path: Renso/Resources/Info.plist
    entitlements:
      path: Renso/Renso.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.denysrumiantsev.Renso
        com.apple.developer.icloud-services:
          - CloudKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.denysrumiantsev.Renso
        PRODUCT_NAME: Renso
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: LJ82247D69
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_FILE: Renso/Resources/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Renso
    dependencies:
      - package: PostHog
    info:
      path: Renso/Resources/Info.plist
      properties:
        UIBackgroundModes:
          - remote-notification
        CFBundleDisplayName: Renso
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"

  RensoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RensoTests
    dependencies:
      - target: Renso
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.denysrumiantsev.RensoTests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Renso.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Renso"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  Renso:
    build:
      targets:
        Renso: all
        RensoTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - RensoTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
